name: Build Android APK

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Use checkout
        uses: actions/checkout@v1
        
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Use flutter action
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.6'
          
      - name: Run pub get
        run: flutter pub get
        working-directory: avtokampi
      
      - name: Build apk
        run: flutter build apk
        working-directory: avtokampi
        
      - name: Release apk artifact
        uses: actions/download-artifact@master
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/

